# Generated by Django 4.2.1 on 2023-06-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=3, max_digits=5)),
                (
                    "disponivel",
                    models.CharField(
                        choices=[("sim", "sim")], default="sim", max_length=100
                    ),
                ),
            ],
        ),
    ]
