# Generated by Django 4.2.1 on 2023-06-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="disponivel",
            field=models.CharField(
                choices=[("sim", "sim"), ("nao", "não")], max_length=100
            ),
        ),
    ]
